spring:
  application:
    name: im-gateway
  main:
    web-application-type: none
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
management:
  endpoints:
    enabled-by-default: false
pulseim:
  im:
    port: ${IM_PORT:8090}
    node-id: ${IM_NODE_ID:node-${IM_PORT:8090}}
  message-service-uri: ${MESSAGE_SERVICE_URI:http://localhost:8085}
  rabbitmq:
    exchange: pulseim.message.events
