package com.pulseim.social;
import com.pulseim.common.api.*; import com.pulseim.common.security.BearerTokens; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/groups") public class GroupController {
 private final GroupRepository groups; private final GroupMemberRepository members; private final GroupEventPublisher events; public GroupController(GroupRepository groups,GroupMemberRepository members,GroupEventPublisher events){this.groups=groups;this.members=members;this.events=events;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public ApiResponse<GroupView> create(@RequestHeader("Authorization")String a,@RequestHeader(value="X-Trace-Id",required=false)String t,@RequestBody CreateGroupCommand c){String u=BearerTokens.require(a).userId();GroupEntity g=groups.save(new GroupEntity("g-"+UUID.randomUUID(),c.name(),u,Instant.now()));members.save(new GroupMemberEntity("gm-"+UUID.randomUUID(),g.id(),u,"OWNER",Instant.now()));events.publish(g.id(),u,"ADDED");return ApiResponse.ok(TraceIds.from(t),GroupView.from(g));}
 @GetMapping public ApiResponse<List<GroupView>> mine(@RequestHeader("Authorization")String a,@RequestHeader(value="X-Trace-Id",required=false)String t){String u=BearerTokens.require(a).userId();return ApiResponse.ok(TraceIds.from(t),groups.findAllById(members.findByUserId(u).stream().map(GroupMemberEntity::groupId).toList()).stream().map(GroupView::from).toList());}
 @PostMapping("/{groupId}/members") @ResponseStatus(HttpStatus.CREATED) public ApiResponse<GroupMemberView> add(@RequestHeader("Authorization")String a,@RequestHeader(value="X-Trace-Id",required=false)String t,@PathVariable String groupId,@RequestBody AddMemberCommand c){requireManager(groupId,BearerTokens.require(a).userId());GroupMemberEntity m=members.findByGroupIdAndUserId(groupId,c.userId()).orElseGet(()->members.save(new GroupMemberEntity("gm-"+UUID.randomUUID(),groupId,c.userId(),"MEMBER",Instant.now())));events.publish(groupId,c.userId(),"ADDED"); return ApiResponse.ok(TraceIds.from(t),GroupMemberView.from(m));}
 @DeleteMapping("/{groupId}/members/{userId}") @ResponseStatus(HttpStatus.NO_CONTENT) public void remove(@RequestHeader("Authorization")String a,@PathVariable String groupId,@PathVariable String userId){requireManager(groupId,BearerTokens.require(a).userId());if(groups.findById(groupId).orElseThrow().ownerId().equals(userId))throw new ResponseStatusException(HttpStatus.CONFLICT,"Owner cannot be removed");members.findByGroupIdAndUserId(groupId,userId).ifPresent(m->{members.delete(m);events.publish(groupId,userId,"REMOVED");});}
 @PostMapping("/{groupId}/members/{userId}/role") public ApiResponse<GroupMemberView> role(@RequestHeader("Authorization")String a,@RequestHeader(value="X-Trace-Id",required=false)String t,@PathVariable String groupId,@PathVariable String userId,@RequestBody RoleCommand c){requireManager(groupId,BearerTokens.require(a).userId());GroupMemberEntity m=members.findByGroupIdAndUserId(groupId,userId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Group member not found"));m.changeRole(("ADMIN".equals(c.role())||"MEMBER".equals(c.role()))?c.role():"MEMBER");return ApiResponse.ok(TraceIds.from(t),GroupMemberView.from(members.save(m)));}
 @GetMapping("/{groupId}/members") public ApiResponse<List<GroupMemberView>> members(@RequestHeader("Authorization")String a,@RequestHeader(value="X-Trace-Id",required=false)String t,@PathVariable String groupId){BearerTokens.require(a);return ApiResponse.ok(TraceIds.from(t),this.members.findByGroupId(groupId).stream().map(GroupMemberView::from).toList());}
 private void requireManager(String g,String u){GroupMemberEntity m=members.findByGroupIdAndUserId(g,u).orElseThrow(()->new ResponseStatusException(HttpStatus.FORBIDDEN,"Group member required"));if(!"OWNER".equals(m.role())&&!"ADMIN".equals(m.role()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Group manager required");}
 public record CreateGroupCommand(String name){} public record AddMemberCommand(String userId,String role){} public record RoleCommand(String role){} public record GroupView(String id,String name,String ownerId,Instant createdAt){static GroupView from(GroupEntity e){return new GroupView(e.id(),e.name(),e.ownerId(),e.createdAt());}} public record GroupMemberView(String id,String groupId,String userId,String role,Instant joinedAt){static GroupMemberView from(GroupMemberEntity e){return new GroupMemberView(e.id(),e.groupId(),e.userId(),e.role(),e.joinedAt());}}
}